# Generated by Django 2.2.24 on 2024-11-01 10:07

from django.db import migrations

def make_new_building(app, schema_editor):
    Flat = app.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year is not None and flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(make_new_building)
    ]
