# Generated by Django 2.2.24 on 2024-11-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20241101_1307'),
        ('property', '0005_auto_20241101_1320'),
    ]

    operations = [
    ]
