# Generated by Django 2.2.24 on 2024-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20241102_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.CharField(max_length=200, verbose_name='ФИО Владельца'),
        ),
    ]
