# Generated by Django 2.2.24 on 2024-11-02 10:14

from django.db import migrations


def make_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            user=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20241102_1254'),
    ]

    operations = [
        migrations.RunPython(make_owner)
    ]
