# Generated by Django 2.2.24 on 2024-11-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20241102_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(to='property.Owner', related_name='flats',
                                         verbose_name='Квартиры в собственности', blank=True),
        ),
    ]
