# Generated by Django 2.2.24 on 2024-11-02 10:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20241102_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Нормализированный номер владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
