# Generated by Django 2.2.24 on 2024-11-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20241102_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnerOwnedFlats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Owner')),
            ],
            options={
                'unique_together': {('owner', 'flat')},
            },
        ),
    ]
