# Generated by Django 2.2.24 on 2024-11-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20241104_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwnerOwnedFlats',
        ),
    ]
